config:
  registries:
    - name: OCIR
      api_url: https://yny.ocir.io
      prefix: yny.ocir.io
      credentials: secret:argocd/ocir-credentials#creds
      default: true
  gitCommitUser: argocd-image-updater[bot]
  gitCommitMail: 2841904+argocd-image-updater[bot]@users.noreply.github.com
  gitCommitTemplate: "build: update image {{ .AppName }} to {{ .NewImage }}"

extraEnv:
  - name: GIT_ASKPASS
    value: /app/git-ask-pass.sh
  - name: GIT_USER
    value: x-access-token
  - name: GIT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: git-creds
        key: password