apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: prometheus
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 48.6.0
    helm:
      releaseName: prometheus
      valueFiles:
      - $values/argocd/prometheus/values.yaml
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/prometheus
    directory:
      include: 'resources.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
