apiVersion: v1
kind: Namespace
metadata:
  name: memowithtags-dev
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memowithtags-server
  labels:
    app: memowithtags-server
  namespace: memowithtags-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memowithtags-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: memowithtags-server
    spec:
      serviceAccountName: memowithtags
      # NOTE: You may need to adapt the following node selectors and tolerations
      # to match the node configuration of your OCI OKE cluster.
      # nodeSelector:
      #   phase: dev
      # tolerations:
      #   - effect: NoSchedule
      #     key: phase
      #     operator: Equal
      #     value: dev
      containers:
        - image: yny.ocir.io/ax1dvc8vmenm/memowithtags-server:17
          name: memowithtags-server
          env:
            - name: JAVA_OPTS
              value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memowithtags
  namespace: memowithtags-dev
  annotations:
    # IMPORTANT: Replace with the OCID of the OCI IAM Role for this service account
    # that is configured for OKE Workload Identity.
    # skip for now
    # iam.oracle.com/oci-iam-role: "ocid1.iamrole.oc1..xxxx"
---
apiVersion: v1
kind: Service
metadata:
  namespace: memowithtags-dev
  name: memowithtags-server
spec:
  type: ClusterIP
  selector:
    app: memowithtags-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: memowithtags-dev
  name: memowithtags-server
spec:
  gateways:
    - istio-gateway/waffle-ingressgateway
    - mesh
  hosts:
    - memowithtags-api-dev.wafflestudio.com
  http:
    - route:
        - destination:
            host: memowithtags-server
